apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ninostyle-ml-tls
spec:
  secretName: ninostyle-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ninostyle.ml
  dnsNames:
    - ninostyle.ml
    - www.ninostyle.ml
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ninostyle.ml
          - www.ninostyle.ml
